### PR TITLE
 Add public API to read and write HDF5

### PR DESCRIPTION
**Pull request by rejsmont**
* DataSetInfo os now in its own namespace.
* HDF5ImageJ now has `hdf5list` method to list contents of HDF5 file
* `hdf5read` and `hdf5write` methods are now more flexible (writers take ImagePlus as argument)
* HDF5_Reader_Vibez now uses abstracted DataSetInfo class
* Proposed version bump to 0.2.0 (as new features were added)

### CODE REVIEW

**Comment by rejsmont** [comment]
This should close #1 :)

**Comment by rejsmont** [comment]
**Do not merge yet! I found a bug!**

**Comment by rejsmont** [comment]
OK - it is now fixed and tested with several HDF5 files!

**Comment by rejsmont** [comment]
Need to include changes introduced by @GFleishman before merging.

**Comment by rejsmont** [comment]
@GFleishman could you please review this PR? Please make sure that links functionality is preserved. Thanks in advance!

**Comment by ctrueden** [comment]
Thanks again @rejsmont, the patch looks good to me. Since it essentially all new API, the chances of breaking backwards compatibility are less. (As far as I could see, no existing public API was broken or changed... right?)

The main thing missing is unit tests, but it's really up to you whether you have time to write any. If you do not have any tests, then future breakages will be harder to detect.

**Comment by rejsmont** [comment]
Accepting this even though no unit tests are present. Will add issue to add unit tests ASAP.

**Pull request merged**
