### PR TITLE
Bump scijava-pom to 31.1.0, jhdf5 to 19.04.0

### PR DESCRIPTION
**Pull request by mkitti**
Replace `ncsa.hdf.hdf5lib.exceptions.HDF5Exception` with `hdf.hdf5lib.exceptions.HDF5Exception` per https://github.com/scijava/pom-scijava/issues/181

### CODE REVIEW

**Comment by mkitti** [comment]
@ctrueden should I just close this now, then?

**Comment by mkitti** [comment]
Yes, I'm going to close.

**Comment by ctrueden** [comment]
@mkitti Sorry to duplicate work. I forgot you had already done this. At least it is updated now.

**Comment by mkitti** [comment]
The diff is saying there might be a trailing space on the master branch.

**Pull request closed without merging**
